name: deer_imitate
description: "https://github.com/simplezhli/flutter_deer"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.4.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.1.0
  sp_util: 2.0.3
  dio: ^5.6.0
  device_info_plus: ^10.1.2
  azlistview: ^2.0.0
  sprintf: ^7.0.0
  rxdart: ^0.28.0
  flutter_swiper_null_safety_flutter3: ^4.0.3
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.4.0
  keyboard_actions: ^4.2.0
  cupertino_icons: ^1.0.8
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/store/
    - assets/images/state/
    - assets/images/order/
    - assets/images/order/dark/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/shop/
    - assets/images/account/
    - assets/images/statistic/
    - assets/lottie/


